<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for views_exposed_form.
 */
function mccarthy_theme_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // target search view
  if (isset($form['#id']) && str_contains($form['#id'], 'views-exposed-form-search-block-1')) {
    
    // Add the use-ajax class directly to the submit button
    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#attributes']['class'][] = 'use-ajax';
    }

    // Set custom placeholder text
    if (isset($form['keys'])) {
      $form['keys']['#attributes']['placeholder'] = t('Search the collection...');
    }
  }
}
