features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
  path: 'public://logo.svg'
favicon:
  use_default: 0
  path: 'public://favicon_0.ico'
  mimetype: image/vnd.microsoft.icon
